### ISSUE TITLE
Flashcards not working

### ISSUE THREAD

**Issue by Rpaixao** [vojtechruz/spring-core-cert-notes-4.2#1]
Hi !

I would like to congratulate you for the amazing resources you published here. They are really clean and explain clearly almost all the base concepts!

However, I was trying to install de flashcards and i can't import the apkg file. 
![captura de ecra 2016-11-27 as 19 09 39](https://cloud.githubusercontent.com/assets/1159505/20651041/3ea7ba2e-b4d5-11e6-87c9-93f67f62e941.png)

Thanks!

**Comment by vojtechruz** [comment]
Thank you for the report, let me check. I should be back shortly.

**Comment by vojtechruz** [comment]
Sorry, seems like I commited incorrect version of the deck, could you please check now? Thanks.

**Comment by Rpaixao** [comment]
Now it works properly!

Thank you very much. Doing the pivotal certification exame next friday. Lets see what happens :P

**Comment by vojtechruz** [comment]
You welcome, thanks for reporting. Don't hesitate to share your experience as a comment to the original blog post after the exam to help others.

Good luck with your certification :)

**Comment by Rpaixao** [comment]
Let me just ask you something. Do you recommend any mock exams to pratice for the real exame?

Thanks in advice!

**Comment by vojtechruz** [comment]
I did not use any, the official slides (based on which are my notes and flashcards) were completely sufficient and there were no trick questions or special types of questions to prepare for. Unlike Oracle java certifications, where mock exams are must :)

**Comment by Rpaixao** [comment]
Yeah, 

I am java 8 SE certified and I must say that without mock exams it would had been really hard to pass on the exam.

Thanks vojtechruz!

**Comment by vojtechruz** [comment]
You welcome, good luck.
